# YOLO数据集配置文件 - 跳一跳游戏目标检测

# 数据集路径（相对路径，相对于项目根目录）
path: yolo_dataset  # 数据集根目录
train: train/images     # 训练图片目录（相对于path）
val: val/images         # 验证图片目录（相对于path）

# 类别数量
nc: 2

# 类别名称
names:
  0: 小人    # 游戏角色
  1: 方块    # 所有方块（包括当前站立和目标跳跃平台）

# 类别描述（用于文档）
class_descriptions:
  小人: "游戏中的角色本体，需要精确检测位置用于计算跳跃起点"
  方块: "游戏中的所有平台方块，包括小人当前站立的和需要跳跃到的目标平台"